unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g mouse on

bind-key h select-pane -L
bind-key l select-pane -R


# Reload conf
bind r source-file ~/.tmux.conf

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key n command-prompt -p "session name:" "new-session -s '%%'"

set -s copy-command 'xclip -in -selection clipboard'
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
run '~/.tmux/plugins/tpm/tpm'

set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
